jobs:
  do-it:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: New File
      run: 'echo "Some test test" >${{ github.workspace }}/Support/test.txt

        ls -l ${{ github.workspace }}/Support

        '
    - continue-on-error: true
      name: Commit
      run: 'git config user.name "GitHub Actions Bot"

        git config user.email "<>"

        git add -A

        git commit -m "test"

        git push origin master

        '
name: Eval features
on:
  repository_dispatch:
    types: trigger-ga___eval.yml
