jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Windows Build with Maven
      run: mvn -B -pl IDE -P complete-win-jar package | egrep -v "^\[INFO\].*?Download.*?http"
    - continue-on-error: true
      name: Remove thin jar
      run: rm ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT.jar
    - continue-on-error: true
      name: Rename fat jar
      run: mv ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT-complete-win.jar
        ${{ github.workspace }}/IDE/target/sikulixwin-2.1.0-SNAPSHOT.jar
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
      name: Publish to OSSRH
      run: mvn -B -e deploy:deploy-file -Dfile='${{ github.workspace }}/IDE/target/sikulixwin-2.1.0-SNAPSHOT.jar'
        -Dpackaging=jar -DgroupId=com.sikulix -DartifactId=sikulixwin -Dversion=2.1.0-SNAPSHOT
        -DrepositoryId=ossrh -Durl='https://oss.sonatype.org/content/repositories/snapshots'
        | egrep -v "^\[INFO\].*?Download.*?http"
    - continue-on-error: true
      name: macOS Build with Maven
      run: mvn -B -pl IDE -P complete-mac-jar clean package | egrep -v "^\[INFO\].*?Download.*?http"
    - continue-on-error: true
      name: Remove thin jar
      run: rm ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT.jar
    - continue-on-error: true
      name: Rename fat jar
      run: mv ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT-complete-mac.jar
        ${{ github.workspace }}/IDE/target/sikulixmac-2.1.0-SNAPSHOT.jar
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
      name: Publish to OSSRH
      run: mvn -B -e deploy:deploy-file -Dfile='${{ github.workspace }}/IDE/target/sikulixmac-2.1.0-SNAPSHOT.jar'
        -Dpackaging=jar -DgroupId=com.sikulix -DartifactId=sikulixmac -Dversion=2.1.0-SNAPSHOT
        -DrepositoryId=ossrh -Durl='https://oss.sonatype.org/content/repositories/snapshots'
        | egrep -v "^\[INFO\].*?Download.*?http"
    - continue-on-error: true
      name: Linux Build with Maven
      run: mvn -B -pl IDE -P complete-lux-jar clean package | egrep -v "^\[INFO\].*?Download.*?http"
    - continue-on-error: true
      name: Remove thin jar
      run: rm ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT.jar
    - continue-on-error: true
      name: Rename fat jar
      run: mv ${{ github.workspace }}/IDE/target/sikulixide-2.1.0-SNAPSHOT-complete-lux.jar
        ${{ github.workspace }}/IDE/target/sikulixlux-2.1.0-SNAPSHOT.jar
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
      name: Publish to OSSRH
      run: mvn -B -e deploy:deploy-file -Dfile='${{ github.workspace }}/IDE/target/sikulixlux-2.1.0-SNAPSHOT.jar'
        -Dpackaging=jar -DgroupId=com.sikulix -DartifactId=sikulixlux -Dversion=2.1.0-SNAPSHOT
        -DrepositoryId=ossrh -Durl='https://oss.sonatype.org/content/repositories/snapshots'
        | egrep -v "^\[INFO\].*?Download.*?http"
    - continue-on-error: true
      name: new latest
      run: bash Support/latestIDE
    - continue-on-error: true
      name: Commit README
      run: 'git config user.name "GitHub Actions Bot"

        git config user.email "<>"

        git add -A

        git commit -m "test"

        git push origin master

        '
name: IDE Snapshot
on:
  repository_dispatch:
    types: trigger-ga___ide-snapshot.yml
